2020-11-01 20:54:35 WARNING (MainThread) [homeassistant.config] Key whitelist_external_dirs has been replaced with allowlist_external_dirs. Please update your config
2020-11-01 20:54:38 WARNING (MainThread) [homeassistant.components.recorder] The 'purge_interval' option is deprecated, please remove it from your configuration
2020-11-01 20:54:38 INFO (MainThread) [homeassistant.setup] Setup of domain logger took 0.0 seconds
2020-11-01 20:54:39 INFO (MainThread) [homeassistant.setup] Setting up http
2020-11-01 20:54:39 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.1 seconds
2020-11-01 20:54:39 INFO (MainThread) [homeassistant.setup] Setting up system_log
2020-11-01 20:54:39 INFO (MainThread) [homeassistant.setup] Setup of domain system_log took 0.0 seconds
2020-11-01 20:54:39 INFO (MainThread) [homeassistant.setup] Setup of domain recorder took 1.0 seconds
2020-11-01 20:54:39 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 1: {'api', 'auth', 'image', 'lovelace', 'search', 'onboarding', 'person', 'system_log', 'frontend', 'device_automation', 'config', 'http', 'hassio', 'websocket_api'}
2020-11-01 20:54:40 INFO (MainThread) [homeassistant.setup] Setting up api
2020-11-01 20:54:40 INFO (MainThread) [homeassistant.setup] Setting up auth
2020-11-01 20:54:40 INFO (MainThread) [homeassistant.setup] Setup of domain auth took 0.0 seconds
2020-11-01 20:54:40 INFO (MainThread) [homeassistant.setup] Setting up lovelace
2020-11-01 20:54:40 INFO (MainThread) [homeassistant.setup] Setting up device_automation
2020-11-01 20:54:40 INFO (MainThread) [homeassistant.setup] Setup of domain device_automation took 0.0 seconds
2020-11-01 20:54:40 INFO (MainThread) [homeassistant.setup] Setting up config
2020-11-01 20:54:40 INFO (MainThread) [homeassistant.setup] Setting up hassio
2020-11-01 20:54:40 INFO (MainThread) [homeassistant.setup] Setting up websocket_api
2020-11-01 20:54:40 INFO (MainThread) [homeassistant.setup] Setup of domain websocket_api took 0.0 seconds
2020-11-01 20:54:41 INFO (MainThread) [homeassistant.setup] Setup of domain api took 1.2 seconds
2020-11-01 20:54:41 INFO (MainThread) [homeassistant.setup] Setting up image
2020-11-01 20:54:41 INFO (MainThread) [homeassistant.setup] Setup of domain config took 1.1 seconds
2020-11-01 20:54:41 INFO (MainThread) [homeassistant.setup] Setup of domain lovelace took 1.2 seconds
2020-11-01 20:54:41 INFO (MainThread) [homeassistant.setup] Setting up search
2020-11-01 20:54:41 INFO (MainThread) [homeassistant.setup] Setup of domain search took 0.0 seconds
2020-11-01 20:54:41 INFO (MainThread) [homeassistant.setup] Setup of domain image took 0.1 seconds
2020-11-01 20:54:41 INFO (MainThread) [homeassistant.setup] Setting up person
2020-11-01 20:54:41 INFO (MainThread) [homeassistant.setup] Setup of domain person took 0.0 seconds
2020-11-01 20:54:41 INFO (MainThread) [homeassistant.setup] Setting up onboarding
2020-11-01 20:54:41 INFO (MainThread) [homeassistant.helpers.storage] Migrating onboarding storage from 1 to 3
2020-11-01 20:54:41 INFO (MainThread) [homeassistant.setup] Setup of domain onboarding took 0.0 seconds
2020-11-01 20:54:41 INFO (SyncWorker_10) [homeassistant.loader] Loaded device_tracker from homeassistant.components.device_tracker
2020-11-01 20:54:41 INFO (SyncWorker_8) [homeassistant.loader] Loaded scene from homeassistant.components.scene
2020-11-01 20:54:41 INFO (SyncWorker_3) [homeassistant.loader] Loaded panel_custom from homeassistant.components.panel_custom
2020-11-01 20:54:41 INFO (SyncWorker_5) [homeassistant.loader] Loaded webhook from homeassistant.components.webhook
2020-11-01 20:54:41 INFO (SyncWorker_21) [homeassistant.loader] Loaded zone from homeassistant.components.zone
2020-11-01 20:54:41 INFO (MainThread) [homeassistant.setup] Setting up frontend
2020-11-01 20:54:41 INFO (MainThread) [homeassistant.setup] Setup of domain frontend took 0.0 seconds
2020-11-01 20:54:41 INFO (MainThread) [homeassistant.setup] Setup of domain hassio took 1.5 seconds
2020-11-01 20:54:41 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 2: {'script', 'mqtt', 'map', 'group', 'zwave', 'history', 'updater', 'binary_sensor', 'shell_command', 'notify', 'cast', 'ffmpeg', 'sensor', 'automation', 'logbook', 'camera', 'system_health'}
2020-11-01 20:54:42 INFO (MainThread) [homeassistant.setup] Setting up map
2020-11-01 20:54:42 INFO (MainThread) [homeassistant.setup] Setup of domain map took 0.0 seconds
2020-11-01 20:54:42 INFO (MainThread) [homeassistant.setup] Setting up group
2020-11-01 20:54:42 INFO (MainThread) [homeassistant.setup] Setting up zwave
2020-11-01 20:54:42 INFO (MainThread) [homeassistant.setup] Setup of domain zwave took 0.0 seconds
2020-11-01 20:54:42 INFO (MainThread) [homeassistant.setup] Setting up history
2020-11-01 20:54:42 INFO (MainThread) [homeassistant.setup] Setup of domain history took 0.0 seconds
2020-11-01 20:54:43 INFO (MainThread) [homeassistant.setup] Setting up updater
2020-11-01 20:54:43 INFO (SyncWorker_7) [homeassistant.loader] Loaded template from homeassistant.components.template
2020-11-01 20:54:43 INFO (MainThread) [homeassistant.setup] Setting up shell_command
2020-11-01 20:54:43 INFO (MainThread) [homeassistant.setup] Setup of domain shell_command took 0.0 seconds
2020-11-01 20:54:43 INFO (SyncWorker_20) [homeassistant.loader] Loaded smtp from homeassistant.components.smtp
2020-11-01 20:54:43 INFO (MainThread) [homeassistant.setup] Setting up ffmpeg
2020-11-01 20:54:43 INFO (MainThread) [homeassistant.setup] Setting up logbook
2020-11-01 20:54:43 INFO (MainThread) [homeassistant.setup] Setting up system_health
2020-11-01 20:54:43 INFO (MainThread) [homeassistant.setup] Setup of domain system_health took 0.0 seconds
2020-11-01 20:54:43 INFO (SyncWorker_16) [homeassistant.loader] Loaded mjpeg from homeassistant.components.mjpeg
2020-11-01 20:54:43 INFO (SyncWorker_3) [homeassistant.loader] Loaded media_source from homeassistant.components.media_source
2020-11-01 20:54:43 INFO (SyncWorker_11) [homeassistant.loader] Loaded cloud from homeassistant.components.cloud
2020-11-01 20:54:43 INFO (SyncWorker_21) [homeassistant.loader] Loaded zeroconf from homeassistant.components.zeroconf
2020-11-01 20:54:43 INFO (SyncWorker_19) [homeassistant.loader] Loaded tts from homeassistant.components.tts
2020-11-01 20:54:43 INFO (SyncWorker_5) [homeassistant.loader] Loaded plex from homeassistant.components.plex
2020-11-01 20:54:50 INFO (MainThread) [homeassistant.components.zwave] Z-Wave USB path is /dev/serial/by-id/usb-0658_0200-if00
2020-11-01 20:54:50 INFO (MainThread) [homeassistant.setup] Setting up notify
2020-11-01 20:54:50 ERROR (MainThread) [haffmpeg.core] FFmpeg fails [Errno 2] No such file or directory: '/usr/bin/avconv'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/haffmpeg/core.py", line 136, in open
    self._proc = await self._loop.run_in_executor(None, proc_func)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/avconv'
2020-11-01 20:54:50 WARNING (MainThread) [haffmpeg.tools] Error starting FFmpeg.
2020-11-01 20:54:50 INFO (MainThread) [homeassistant.setup] Setup of domain ffmpeg took 6.9 seconds
2020-11-01 20:54:50 INFO (MainThread) [homeassistant.setup] Setting up script
2020-11-01 20:54:51 INFO (MainThread) [homeassistant.setup] Setting up mqtt
2020-11-01 20:54:51 INFO (MainThread) [homeassistant.setup] Setup of domain mqtt took 0.0 seconds
2020-11-01 20:54:51 INFO (MainThread) [homeassistant.setup] Setting up camera
2020-11-01 20:54:51 INFO (MainThread) [homeassistant.components.notify] Setting up notify.smtp
2020-11-01 20:54:51 INFO (MainThread) [homeassistant.setup] Setup of domain logbook took 8.3 seconds
2020-11-01 20:54:52 INFO (SyncWorker_12) [homeassistant.loader] Loaded systemmonitor from homeassistant.components.systemmonitor
2020-11-01 20:54:52 INFO (MainThread) [homeassistant.setup] Setup of domain updater took 9.0 seconds
2020-11-01 20:54:52 INFO (SyncWorker_14) [homeassistant.loader] Loaded media_player from homeassistant.components.media_player
2020-11-01 20:54:52 INFO (SyncWorker_0) [homeassistant.loader] Loaded alexa from homeassistant.components.alexa
2020-11-01 20:54:52 INFO (SyncWorker_7) [homeassistant.loader] Loaded google_assistant from homeassistant.components.google_assistant
2020-11-01 20:54:52 INFO (SyncWorker_20) [homeassistant.loader] Loaded sonos from homeassistant.components.sonos
2020-11-01 20:54:53 INFO (MainThread) [homeassistant.setup] Setting up binary_sensor
2020-11-01 20:54:53 INFO (MainThread) [homeassistant.setup] Setup of domain binary_sensor took 0.0 seconds
2020-11-01 20:54:53 WARNING (MainThread) [homeassistant.setup] Setup of group is taking over 10 seconds.
2020-11-01 20:54:53 INFO (MainThread) [homeassistant.setup] Setup of domain script took 2.6 seconds
2020-11-01 20:54:53 INFO (SyncWorker_3) [homeassistant.loader] Loaded climate from homeassistant.components.climate
2020-11-01 20:54:53 INFO (SyncWorker_10) [homeassistant.loader] Loaded time_date from homeassistant.components.time_date
2020-11-01 20:54:53 INFO (SyncWorker_5) [homeassistant.loader] Loaded light from homeassistant.components.light
2020-11-01 20:54:53 INFO (SyncWorker_19) [homeassistant.loader] Loaded lock from homeassistant.components.lock
2020-11-01 20:54:53 INFO (SyncWorker_2) [homeassistant.loader] Loaded switch from homeassistant.components.switch
2020-11-01 20:54:53 INFO (SyncWorker_21) [homeassistant.loader] Loaded fan from homeassistant.components.fan
2020-11-01 20:54:53 INFO (SyncWorker_11) [homeassistant.loader] Loaded cover from homeassistant.components.cover
2020-11-01 20:54:53 INFO (MainThread) [homeassistant.setup] Setup of domain camera took 2.1 seconds
2020-11-01 20:54:53 INFO (Thread-3) [homeassistant.components.mqtt] Connected to MQTT server 10.1.2.89:1883 (0)
2020-11-01 20:54:53 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.zwave
2020-11-01 20:54:53 INFO (SyncWorker_1) [homeassistant.loader] Loaded ssdp from homeassistant.components.ssdp
2020-11-01 20:54:53 INFO (MainThread) [homeassistant.setup] Setting up climate
2020-11-01 20:54:53 INFO (MainThread) [homeassistant.setup] Setup of domain climate took 0.0 seconds
2020-11-01 20:54:53 INFO (MainThread) [homeassistant.setup] Setting up light
2020-11-01 20:54:53 INFO (SyncWorker_13) [homeassistant.loader] Loaded worldclock from homeassistant.components.worldclock
2020-11-01 20:54:53 INFO (MainThread) [homeassistant.setup] Setting up lock
2020-11-01 20:54:53 INFO (MainThread) [homeassistant.setup] Setup of domain lock took 0.0 seconds
2020-11-01 20:54:53 INFO (MainThread) [homeassistant.setup] Setting up switch
2020-11-01 20:54:53 INFO (MainThread) [homeassistant.setup] Setup of domain switch took 0.0 seconds
2020-11-01 20:54:53 INFO (MainThread) [homeassistant.setup] Setting up fan
2020-11-01 20:54:53 INFO (MainThread) [homeassistant.setup] Setup of domain fan took 0.0 seconds
2020-11-01 20:54:53 INFO (MainThread) [homeassistant.setup] Setting up cover
2020-11-01 20:54:53 INFO (MainThread) [homeassistant.setup] Setup of domain cover took 0.0 seconds
2020-11-01 20:54:53 INFO (MainThread) [homeassistant.setup] Setup of domain group took 11.8 seconds
2020-11-01 20:54:53 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.updater
2020-11-01 20:54:53 INFO (MainThread) [homeassistant.setup] Setting up automation
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.components.climate] Setting up climate.zwave
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.setup] Setting up sensor
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.setup] Setup of domain sensor took 0.0 seconds
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.setup] Setup of domain light took 1.0 seconds
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.components.lock] Setting up lock.zwave
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.components.switch] Setting up switch.zwave
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.components.fan] Setting up fan.zwave
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.components.cover] Setting up cover.zwave
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.mqtt
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.mqtt
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.mqtt
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.mqtt
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.mqtt
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.mqtt
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.mqtt
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.mqtt
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.mqtt
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.systemmonitor
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.time_date
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.worldclock
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.template
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.zwave
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.components.light] Setting up light.zwave
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.template
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.template
2020-11-01 20:54:54 INFO (MainThread) [homeassistant.setup] Setup of domain notify took 4.6 seconds
2020-11-01 20:54:55 INFO (MainThread) [homeassistant.setup] Setting up cast
2020-11-01 20:54:55 INFO (MainThread) [homeassistant.setup] Setup of domain cast took 0.0 seconds
2020-11-01 20:54:55 INFO (MainThread) [homeassistant.setup] Setting up media_player
2020-11-01 20:54:55 INFO (MainThread) [homeassistant.setup] Setup of domain media_player took 0.0 seconds
2020-11-01 20:54:55 INFO (MainThread) [homeassistant.setup] Setup of domain automation took 1.7 seconds
2020-11-01 20:54:56 INFO (MainThread) [homeassistant.components.media_player] Setting up media_player.cast
2020-11-01 20:54:56 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 20.92s
2020-11-01 20:54:56 INFO (MainThread) [homeassistant.core] Starting Home Assistant
2020-11-01 20:54:56 INFO (SyncWorker_16) [homeassistant.components.zwave] Starting Z-Wave network...
2020-11-01 20:54:56 INFO (SyncWorker_16) [openzwave] Start Openzwave network.
2020-11-01 20:54:56 INFO (MainThread) [homeassistant.core] Timer:starting
2020-11-01 20:54:56 INFO (MainThread) [homeassistant.components.updater] Submitted analytics to Home Assistant servers. Information submitted includes {'installation_type': 'Home Assistant OS', 'version': '0.117.2', 'dev': False, 'hassio': True, 'virtualenv': False, 'python_version': '3.8.6', 'docker': True, 'arch': 'armv7l', 'timezone': 'America/Toronto', 'os_name': 'Linux', 'os_version': '3.12.0', 'supervisor': '2020.10.0', 'host_os': 'HassOS 4.15', 'chassis': 'embedded', 'docker_version': '19.03.11', 'distribution': 'alpine', 'huuid': '3101311b0f0a431caaa266901c46204d'}
2020-11-01 20:54:56 INFO (Dummy-7) [openzwave] Driver ready using library Static Controller version Z-Wave 3.95
2020-11-01 20:54:56 INFO (Dummy-7) [openzwave] home_id 0xdf2f20c2, controller node id is 1
2020-11-01 20:54:56 INFO (MainThread) [homeassistant.components.automation.turn_off_neo3_if_neo2_on] Initialized trigger Turn off Neo3 if Neo2 on
2020-11-01 20:54:56 INFO (MainThread) [homeassistant.components.automation.turn_off_inovellisw2_3_minutes_after_last_movement] Initialized trigger Turn off OfficeLight after 3 minutes no motion
2020-11-01 20:54:56 INFO (MainThread) [homeassistant.components.automation.door_is_open] Initialized trigger Door is open
2020-11-01 20:54:56 INFO (MainThread) [homeassistant.components.automation.turn_on_inovellisw2_when_there_is_movement] Initialized trigger Turn on InovelliSW2 when there is movement
2020-11-01 20:54:56 INFO (MainThread) [homeassistant.components.automation.turn_on_zooz01_when_there_is_movement] Initialized trigger Turn on Zooz01 when there is movement
2020-11-01 20:54:56 INFO (MainThread) [homeassistant.components.automation.turn_off_zooz01_5_minutes_after_last_movement] Initialized trigger Turn off Zooz01 5 minutes after last movement
2020-11-01 20:54:56 INFO (MainThread) [homeassistant.components.automation.switch_of_water] Initialized trigger Switch of Water
2020-11-01 20:56:32 INFO (Dummy-7) [homeassistant.components.zwave] Z-Wave network is ready for use. All awake nodes have been queried. Sleeping nodes will be queried when they awake
2020-11-01 20:56:33 INFO (MainThread) [homeassistant.components.zwave] Z-Wave ready after 96 seconds
2020-11-01 20:56:33 INFO (SyncWorker_11) [homeassistant.components.zwave] Z-Wave polling interval set to 30000 ms
2020-11-01 21:18:47 INFO (MainThread) [homeassistant.components.automation.door_is_open] Door is open: Running automation actions
2020-11-01 21:18:47 INFO (MainThread) [homeassistant.components.automation.door_is_open] Door is open: Executing step call service
2020-11-01 21:18:47 INFO (MainThread) [homeassistant.components.automation.turn_on_inovellisw2_when_there_is_movement] Turn on InovelliSW2 when there is movement: Running automation actions
2020-11-01 21:18:47 INFO (MainThread) [homeassistant.components.automation.turn_on_inovellisw2_when_there_is_movement] Turn on InovelliSW2 when there is movement: Executing step call service
2020-11-01 21:18:47 INFO (MainThread) [homeassistant.components.automation.door_is_open] Door is open: Executing step call service
2020-11-01 21:18:47 INFO (MainThread) [homeassistant.components.automation.turn_on_inovellisw2_when_there_is_movement] Turn on InovelliSW2 when there is movement: Executing step call service
2020-11-01 21:18:48 INFO (MainThread) [homeassistant.components.automation.door_is_open] Door is open: Executing step call service
2020-11-01 21:18:50 INFO (MainThread) [homeassistant.components.automation.turn_on_inovellisw2_when_there_is_movement] Turn on InovelliSW2 when there is movement: Executing step call service
2020-11-01 21:18:50 INFO (MainThread) [homeassistant.components.automation.door_is_open] Door is open: Executing step call service
2020-11-01 21:18:50 ERROR (MainThread) [homeassistant.components.automation.door_is_open] Door is open: Error executing script. Unexpected error for call_service at pos 4: [Errno 2] No such file or directory: '/usr/bin/convert'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/shell_command/__init__.py", line 80, in async_service_handler
    process = await create_process
  File "/usr/local/lib/python3.8/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/local/lib/python3.8/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/convert'
2020-11-01 21:18:50 ERROR (MainThread) [homeassistant.components.automation.door_is_open] While executing automation automation.door_is_open
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 426, in async_trigger
    await self.action_script.async_run(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1010, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 245, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/shell_command/__init__.py", line 80, in async_service_handler
    process = await create_process
  File "/usr/local/lib/python3.8/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/local/lib/python3.8/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/convert'
2020-11-01 21:18:51 INFO (MainThread) [homeassistant.components.automation.turn_on_inovellisw2_when_there_is_movement] Turn on InovelliSW2 when there is movement: Executing step call service
2020-11-01 21:18:51 ERROR (MainThread) [homeassistant.components.automation.turn_on_inovellisw2_when_there_is_movement] Turn on InovelliSW2 when there is movement: Error executing script. Unexpected error for call_service at pos 4: [Errno 2] No such file or directory: '/usr/bin/convert'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/shell_command/__init__.py", line 80, in async_service_handler
    process = await create_process
  File "/usr/local/lib/python3.8/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/local/lib/python3.8/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/convert'
2020-11-01 21:18:51 ERROR (MainThread) [homeassistant.components.automation.turn_on_inovellisw2_when_there_is_movement] While executing automation automation.turn_on_inovellisw2_when_there_is_movement
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 426, in async_trigger
    await self.action_script.async_run(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1010, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 245, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/shell_command/__init__.py", line 80, in async_service_handler
    process = await create_process
  File "/usr/local/lib/python3.8/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/local/lib/python3.8/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/convert'
2020-11-01 22:11:45 INFO (MainThread) [homeassistant.components.websocket_api.http.connection.1849011504] Connection closed by client
2020-11-02 17:38:06 INFO (Dummy-7) [homeassistant.components.zwave] Z-Wave network is complete. All nodes on the network have been queried
2020-11-02 20:54:58 INFO (MainThread) [homeassistant.components.updater] Submitted analytics to Home Assistant servers. Information submitted includes {'installation_type': 'Home Assistant OS', 'version': '0.117.2', 'dev': False, 'hassio': True, 'virtualenv': False, 'python_version': '3.8.6', 'docker': True, 'arch': 'armv7l', 'timezone': 'America/Toronto', 'os_name': 'Linux', 'os_version': '3.12.0', 'supervisor': '2020.10.1', 'host_os': 'HassOS 4.15', 'chassis': 'embedded', 'docker_version': '19.03.11', 'distribution': 'alpine', 'huuid': '3101311b0f0a431caaa266901c46204d'}
2020-11-03 01:44:55 INFO (MainThread) [homeassistant.components.websocket_api.http.connection.1849015384] Connection closed by client
2020-11-03 20:54:58 INFO (MainThread) [homeassistant.components.updater] Submitted analytics to Home Assistant servers. Information submitted includes {'installation_type': 'Home Assistant OS', 'version': '0.117.2', 'dev': False, 'hassio': True, 'virtualenv': False, 'python_version': '3.8.6', 'docker': True, 'arch': 'armv7l', 'timezone': 'America/Toronto', 'os_name': 'Linux', 'os_version': '3.12.0', 'supervisor': '2020.10.1', 'host_os': 'HassOS 4.15', 'chassis': 'embedded', 'docker_version': '19.03.11', 'distribution': 'alpine', 'huuid': '3101311b0f0a431caaa266901c46204d'}
2020-11-03 22:36:41 INFO (MainThread) [homeassistant.components.websocket_api.http.connection.1830606328] Connection closed by client
2020-11-04 20:54:58 INFO (MainThread) [homeassistant.components.updater] Submitted analytics to Home Assistant servers. Information submitted includes {'installation_type': 'Home Assistant OS', 'version': '0.117.2', 'dev': False, 'hassio': True, 'virtualenv': False, 'python_version': '3.8.6', 'docker': True, 'arch': 'armv7l', 'timezone': 'America/Toronto', 'os_name': 'Linux', 'os_version': '3.12.0', 'supervisor': '2020.11.0', 'host_os': 'HassOS 4.15', 'chassis': 'embedded', 'docker_version': '19.03.11', 'distribution': 'alpine', 'huuid': '3101311b0f0a431caaa266901c46204d'}
2020-11-05 01:13:53 INFO (MainThread) [homeassistant.components.websocket_api.http.connection.1851842768] Connection closed by client
2020-11-05 17:07:41 INFO (MainThread) [homeassistant.components.automation.door_is_open] Door is open: Running automation actions
2020-11-05 17:07:41 INFO (MainThread) [homeassistant.components.automation.door_is_open] Door is open: Executing step call service
2020-11-05 17:07:41 INFO (MainThread) [homeassistant.components.automation.turn_on_inovellisw2_when_there_is_movement] Turn on InovelliSW2 when there is movement: Running automation actions
2020-11-05 17:07:41 INFO (MainThread) [homeassistant.components.automation.turn_on_inovellisw2_when_there_is_movement] Turn on InovelliSW2 when there is movement: Executing step call service
2020-11-05 17:07:41 INFO (MainThread) [homeassistant.components.automation.door_is_open] Door is open: Executing step call service
2020-11-05 17:07:41 INFO (MainThread) [homeassistant.components.automation.turn_on_inovellisw2_when_there_is_movement] Turn on InovelliSW2 when there is movement: Executing step call service
2020-11-05 17:07:42 INFO (MainThread) [homeassistant.components.automation.door_is_open] Door is open: Executing step call service
2020-11-05 17:07:43 INFO (MainThread) [homeassistant.components.automation.turn_on_inovellisw2_when_there_is_movement] Turn on InovelliSW2 when there is movement: Executing step call service
2020-11-05 17:07:44 INFO (MainThread) [homeassistant.components.automation.door_is_open] Door is open: Executing step call service
2020-11-05 17:07:44 ERROR (MainThread) [homeassistant.components.automation.door_is_open] Door is open: Error executing script. Unexpected error for call_service at pos 4: [Errno 2] No such file or directory: '/usr/bin/convert'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/shell_command/__init__.py", line 80, in async_service_handler
    process = await create_process
  File "/usr/local/lib/python3.8/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/local/lib/python3.8/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/convert'
2020-11-05 17:07:44 ERROR (MainThread) [homeassistant.components.automation.door_is_open] While executing automation automation.door_is_open
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 426, in async_trigger
    await self.action_script.async_run(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1010, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 245, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/shell_command/__init__.py", line 80, in async_service_handler
    process = await create_process
  File "/usr/local/lib/python3.8/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/local/lib/python3.8/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/convert'
2020-11-05 17:07:44 INFO (MainThread) [homeassistant.components.automation.turn_on_inovellisw2_when_there_is_movement] Turn on InovelliSW2 when there is movement: Executing step call service
2020-11-05 17:07:44 ERROR (MainThread) [homeassistant.components.automation.turn_on_inovellisw2_when_there_is_movement] Turn on InovelliSW2 when there is movement: Error executing script. Unexpected error for call_service at pos 4: [Errno 2] No such file or directory: '/usr/bin/convert'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/shell_command/__init__.py", line 80, in async_service_handler
    process = await create_process
  File "/usr/local/lib/python3.8/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/local/lib/python3.8/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/convert'
2020-11-05 17:07:44 ERROR (MainThread) [homeassistant.components.automation.turn_on_inovellisw2_when_there_is_movement] While executing automation automation.turn_on_inovellisw2_when_there_is_movement
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 426, in async_trigger
    await self.action_script.async_run(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1010, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 245, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/shell_command/__init__.py", line 80, in async_service_handler
    process = await create_process
  File "/usr/local/lib/python3.8/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/local/lib/python3.8/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/convert'
2020-11-05 20:54:58 INFO (MainThread) [homeassistant.components.updater] Submitted analytics to Home Assistant servers. Information submitted includes {'installation_type': 'Home Assistant OS', 'version': '0.117.2', 'dev': False, 'hassio': True, 'virtualenv': False, 'python_version': '3.8.6', 'docker': True, 'arch': 'armv7l', 'timezone': 'America/Toronto', 'os_name': 'Linux', 'os_version': '3.12.0', 'supervisor': '2020.11.0', 'host_os': 'HassOS 4.15', 'chassis': 'embedded', 'docker_version': '19.03.11', 'distribution': 'alpine', 'huuid': '3101311b0f0a431caaa266901c46204d'}
2020-11-06 01:35:51 INFO (MainThread) [homeassistant.components.websocket_api.http.connection.1851928552] Connection closed by client
2020-11-06 12:32:37 INFO (MainThread) [homeassistant.components.automation.door_is_open] Door is open: Running automation actions
2020-11-06 12:32:37 INFO (MainThread) [homeassistant.components.automation.door_is_open] Door is open: Executing step call service
2020-11-06 12:32:37 INFO (MainThread) [homeassistant.components.automation.turn_on_inovellisw2_when_there_is_movement] Turn on InovelliSW2 when there is movement: Running automation actions
2020-11-06 12:32:37 INFO (MainThread) [homeassistant.components.automation.turn_on_inovellisw2_when_there_is_movement] Turn on InovelliSW2 when there is movement: Executing step call service
2020-11-06 12:32:37 INFO (MainThread) [homeassistant.components.automation.door_is_open] Door is open: Executing step call service
2020-11-06 12:32:37 INFO (MainThread) [homeassistant.components.automation.turn_on_inovellisw2_when_there_is_movement] Turn on InovelliSW2 when there is movement: Executing step call service
2020-11-06 12:32:38 INFO (MainThread) [homeassistant.components.automation.door_is_open] Door is open: Executing step call service
2020-11-06 12:32:39 INFO (MainThread) [homeassistant.components.automation.turn_on_inovellisw2_when_there_is_movement] Turn on InovelliSW2 when there is movement: Executing step call service
2020-11-06 12:32:39 INFO (MainThread) [homeassistant.components.automation.door_is_open] Door is open: Executing step call service
2020-11-06 12:32:39 ERROR (MainThread) [homeassistant.components.automation.door_is_open] Door is open: Error executing script. Unexpected error for call_service at pos 4: [Errno 2] No such file or directory: '/usr/bin/convert'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/shell_command/__init__.py", line 80, in async_service_handler
    process = await create_process
  File "/usr/local/lib/python3.8/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/local/lib/python3.8/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/convert'
2020-11-06 12:32:39 ERROR (MainThread) [homeassistant.components.automation.door_is_open] While executing automation automation.door_is_open
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 426, in async_trigger
    await self.action_script.async_run(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1010, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 245, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/shell_command/__init__.py", line 80, in async_service_handler
    process = await create_process
  File "/usr/local/lib/python3.8/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/local/lib/python3.8/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/convert'
2020-11-06 12:32:40 INFO (MainThread) [homeassistant.components.automation.turn_on_inovellisw2_when_there_is_movement] Turn on InovelliSW2 when there is movement: Executing step call service
2020-11-06 12:32:40 ERROR (MainThread) [homeassistant.components.automation.turn_on_inovellisw2_when_there_is_movement] Turn on InovelliSW2 when there is movement: Error executing script. Unexpected error for call_service at pos 4: [Errno 2] No such file or directory: '/usr/bin/convert'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/shell_command/__init__.py", line 80, in async_service_handler
    process = await create_process
  File "/usr/local/lib/python3.8/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/local/lib/python3.8/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/convert'
2020-11-06 12:32:40 ERROR (MainThread) [homeassistant.components.automation.turn_on_inovellisw2_when_there_is_movement] While executing automation automation.turn_on_inovellisw2_when_there_is_movement
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 426, in async_trigger
    await self.action_script.async_run(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1010, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 245, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/shell_command/__init__.py", line 80, in async_service_handler
    process = await create_process
  File "/usr/local/lib/python3.8/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/local/lib/python3.8/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/convert'
2020-11-06 13:35:25 INFO (MainThread) [homeassistant.components.websocket_api.http.connection.1849135336] Connection closed by client
2020-11-06 15:36:14 INFO (MainThread) [homeassistant.components.notify] Setting up notify.smtp
2020-11-06 15:36:14 ERROR (SyncWorker_5) [homeassistant.components.smtp.notify] Login not possible. Please check your setting and/or your credentials
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/smtp/notify.py", line 141, in connection_is_valid
    server = self.connect()
  File "/usr/src/homeassistant/homeassistant/components/smtp/notify.py", line 134, in connect
    mail.login(self.username, self.password)
  File "/usr/local/lib/python3.8/smtplib.py", line 734, in login
    raise last_exception
  File "/usr/local/lib/python3.8/smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "/usr/local/lib/python3.8/smtplib.py", line 646, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials o124sm1659571ila.62 - gsmtp')
2020-11-06 15:36:14 ERROR (MainThread) [homeassistant.components.notify] Failed to initialize notification service smtp
2020-11-06 15:36:21 INFO (MainThread) [homeassistant.components.script.test_notification] Gmail Notification: Running script sequence
2020-11-06 15:36:21 INFO (MainThread) [homeassistant.components.script.test_notification] Gmail Notification: Executing step call service
2020-11-06 15:36:21 ERROR (MainThread) [homeassistant.components.script.test_notification] Gmail Notification: Error executing script. Service not found for call_service at pos 1: Unable to find service notify/mailtopykodel
2020-11-06 15:36:21 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1010, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 245, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1398, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service notify/mailtopykodel
2020-11-06 15:38:11 INFO (MainThread) [homeassistant.components.script.test_notification] Gmail Notification: Running script sequence
2020-11-06 15:38:11 INFO (MainThread) [homeassistant.components.script.test_notification] Gmail Notification: Executing step call service
2020-11-06 15:38:11 ERROR (MainThread) [homeassistant.components.script.test_notification] Gmail Notification: Error executing script. Service not found for call_service at pos 1: Unable to find service notify/mailtopykodel
2020-11-06 15:38:11 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1010, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 245, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1398, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service notify/mailtopykodel
2020-11-06 15:38:34 INFO (MainThread) [homeassistant.components.script.test_notification] Gmail Notification: Running script sequence
2020-11-06 15:38:34 INFO (MainThread) [homeassistant.components.script.test_notification] Gmail Notification: Executing step call service
2020-11-06 15:38:34 ERROR (MainThread) [homeassistant.components.script.test_notification] Gmail Notification: Error executing script. Service not found for call_service at pos 1: Unable to find service notify/mailtopykodel
2020-11-06 15:38:34 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1010, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 245, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1398, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service notify/mailtopykodel
2020-11-06 15:39:21 INFO (MainThread) [homeassistant.components.notify] Setting up notify.smtp
2020-11-06 15:39:26 INFO (MainThread) [homeassistant.components.script.test_notification] Gmail Notification: Running script sequence
2020-11-06 15:39:26 INFO (MainThread) [homeassistant.components.script.test_notification] Gmail Notification: Executing step call service
2020-11-06 19:41:00 INFO (MainThread) [homeassistant.components.websocket_api.http.connection.1849135840] Connection closed by client
2020-11-06 20:54:58 INFO (MainThread) [homeassistant.components.updater] Submitted analytics to Home Assistant servers. Information submitted includes {'installation_type': 'Home Assistant OS', 'version': '0.117.2', 'dev': False, 'hassio': True, 'virtualenv': False, 'python_version': '3.8.6', 'docker': True, 'arch': 'armv7l', 'timezone': 'America/Toronto', 'os_name': 'Linux', 'os_version': '3.12.0', 'supervisor': '2020.11.0', 'host_os': 'HassOS 4.15', 'chassis': 'embedded', 'docker_version': '19.03.11', 'distribution': 'alpine', 'huuid': '3101311b0f0a431caaa266901c46204d'}
2020-11-07 02:28:31 INFO (MainThread) [homeassistant.components.websocket_api.http.connection.1830555576] Connection closed by client
2020-11-07 02:29:57 INFO (MainThread) [homeassistant.components.websocket_api.http.connection.1851672776] Connection closed by client
2020-11-07 20:54:58 INFO (MainThread) [homeassistant.components.updater] Submitted analytics to Home Assistant servers. Information submitted includes {'installation_type': 'Home Assistant OS', 'version': '0.117.2', 'dev': False, 'hassio': True, 'virtualenv': False, 'python_version': '3.8.6', 'docker': True, 'arch': 'armv7l', 'timezone': 'America/Toronto', 'os_name': 'Linux', 'os_version': '3.12.0', 'supervisor': '2020.11.0', 'host_os': 'HassOS 4.15', 'chassis': 'embedded', 'docker_version': '19.03.11', 'distribution': 'alpine', 'huuid': '3101311b0f0a431caaa266901c46204d'}
2020-11-07 22:46:04 INFO (MainThread) [homeassistant.components.websocket_api.http.connection.1851928144] Connection closed by client
2020-11-07 23:43:24 INFO (MainThread) [homeassistant.components.websocket_api.http.connection.1849009512] Connection closed by client
2020-11-08 20:54:58 INFO (MainThread) [homeassistant.components.updater] Submitted analytics to Home Assistant servers. Information submitted includes {'installation_type': 'Home Assistant OS', 'version': '0.117.2', 'dev': False, 'hassio': True, 'virtualenv': False, 'python_version': '3.8.6', 'docker': True, 'arch': 'armv7l', 'timezone': 'America/Toronto', 'os_name': 'Linux', 'os_version': '3.12.0', 'supervisor': '2020.11.0', 'host_os': 'HassOS 4.15', 'chassis': 'embedded', 'docker_version': '19.03.11', 'distribution': 'alpine', 'huuid': '3101311b0f0a431caaa266901c46204d'}
2020-11-09 20:54:58 INFO (MainThread) [homeassistant.components.updater] Submitted analytics to Home Assistant servers. Information submitted includes {'installation_type': 'Home Assistant OS', 'version': '0.117.2', 'dev': False, 'hassio': True, 'virtualenv': False, 'python_version': '3.8.6', 'docker': True, 'arch': 'armv7l', 'timezone': 'America/Toronto', 'os_name': 'Linux', 'os_version': '3.12.0', 'supervisor': '2020.11.0', 'host_os': 'HassOS 4.15', 'chassis': 'embedded', 'docker_version': '19.03.11', 'distribution': 'alpine', 'huuid': '3101311b0f0a431caaa266901c46204d'}
